name: sar
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip

  # Core libs via conda
  - numpy
  - pytorch
  - gymnasium
  - mujoco
  - imageio

  # Stuff that’s easier / standard via pip
  - pip:
      - ray[rllib]
      - mujoco-python-viewer
